<hr/>
<div id="footer_row" class="row">
	<div class="col-sm-9">
	  <div class="col-sm-3">
	    <p><strong><?=$this->transEsc('FID Darstellende Kunst')?></strong></p>
	    <ul>
			<li><a href="/vufind/spages/uber"><?=$this->transEsc('Über uns')?></a></li>
			<li><a href="/vufind/spages/beirat"><?=$this->transEsc('Wissenschaftlicher Beirat')?></a></li>
			<li><a href="/vufind/spages/netzwerke"><?=$this->transEsc('Netzwerke')?></a></li>
			<li><a href="/vufind/spages/dokumentation"><?=$this->transEsc('Dokumentation')?></a></li>
			<li><a href="/vufind/spages/downloads"><?=$this->transEsc('Downloads')?></a></li>			
	    </ul>
	  </div>
	  <div class="col-sm-3">
	    <p><strong><?=$this->transEsc('Fachservice')?></strong></p>
	    <ul>
			<li><a href="/vufind/spages/kontakt"><?=$this->transEsc('Kontakt')?></a></li>
			<li><a href="/vufind/spages/suchen"><?=$this->transEsc('Suchen im FID-Portal')?></a></li>
			<li><a href="/vufind/spages/news"><?=$this->transEsc('News')?></a></li>
			<li><a href="/vufind/spages/themen"><?=$this->transEsc('Dossiers, Themen')?></a></li>
	    </ul>
	  </div>
	  <div class="col-sm-3">
	    <p><strong><?=$this->transEsc('Bibliothekarische Dienste')?></strong></p>
	    <ul>
	    <li><a href="/vufind/spages/contents"><?=$this->transEsc('Online Contents')?></a></li>
	    <li><a href="/vufind/spages/neuerwerb"><?=$this->transEsc('Neuerwerbungen')?></a></li>
	    <li><a href="/vufind/spages/fernleihe"><?=$this->transEsc('Fernleihe')?></a></li>
	    <li><a href="/vufind/spages/kaufvorschlag"><?=$this->transEsc('Kaufvorschlag')?></a></li>	
	    </ul>
	  </div>
	  	  <div class="col-sm-3">
	    <p><strong><?=$this->transEsc('Rechtliches')?></strong></p>
	    <ul>
			<li><a href="/vufind/spages/impressum"><?=$this->transEsc('Impressum')?></a></li>
			<li><a href="/vufind/spages/copyright"><?=$this->transEsc('Copyright')?></a></li>
			<li><a href="/vufind/spages/verweise"><?=$this->transEsc('Verweise und Links')?></a></li>
			<li><a href="/vufind/spages/datenschutz"><?=$this->transEsc('Datenschutz')?></a></li>
			<li><a href="/vufind/spages/haftung"><?=$this->transEsc('Haftungshinweis')?></a></li>
	    </ul>
	  </div>
   </div>
   <div class="col-sm-3 bottom_logos">
  </div>
</div>
